from datamodel import OrderDepth, UserId, TradingState, Order, ConversionObservation
from typing import List
import string
import jsonpickle
import numpy as np
import math

ROSES_TRADES = "hhshhhhhhhbhshhhbshhhhhbbhhhhssbhhbssbshhhhhhhbbhhhhhshbhhsbhhhhhhshbhhhshbhsbhhshbhhhhhhsshbhbhhhhhshhhbhhssbbhhshbhsshbbhshhbhshhbsbhhhshbsshhbhbhhhhhhsshhhbbhhhhhhhhsshhhbbhhhhhssbhhshbhhhshhhhhhhbshhbbhhhshbhhhhhhhhhhhhhhsshhbhbhhhhsbhhhhssbbhhhhhsshhbhbssbsbbhhhsshhhhhbhhhhsbhhbhsbsbhhsbhshshhhhhhhbbhhshbhhhhsshhhbshhhbbhhhsshhbbhhhhhssbhshbhbhhsbshsbhhbhshshhhhhhhhhhbsbbhhhhhhhhsbhshhhshhhhbhbsshhhhhhbhhshbbsshhbshbbhhhshshhhhbshhhhhbshhhhbbsbhhshbsshhhhbbhhshbhhsshbbshbshhshhhhhhhhhhhhbhbhhhhsbsbshhhshhbhshhhhhhhhhhhhbbhshshbbsshhbbsshhhbshhhhhhhhhhhhbbhhhshhshbbhhsshhhbbhhhhsshhhhhhbsbshhhhhhhhhhhhbhshhbshhhhhbhhhshhhbhhhshbsbhshhbbhsshhhhbbshshbsbhshhhbhhhshbbhsshbbhsshbbhhhsshhhhhhhhhhhhhhhbshbsbhhbhhhhhsbsbhshshhbbhhshhshbshhhbhshbbhhhhhhhhhhsshhbbshbhhsshhhhhhhbbhhhhhhhhhhhsshhhhbshhbbhhsbhhhhsshhhhhbbhhhhhshshbbhsbhhssbsbshhbbhsshbshhhhhhbbhhhsbhsshbhhshhbbhhhhhhhhsbhhhshhbhhhsbhsbhsbhshhbhsshhhhbsbbhhhhhsbhhhhhhhhhsshbbhhhhhhhhsbhhhhhhhhhshhhhsbsbbhhhhsbhssbhsbsbhshhhbsbbhhhhhhsbhhhhhhsshbbhhsshhhhhbhhhsbshhhhhbhhshbhshbbhhhhhhhhhshshbbhhhsshhhhbshhhhhhhhhhbhshhhhhhhhbbhshbhhhshhshhhhbshhbshhhhhbhsbbhhsbsbhhhsshhhhbbsshhhhhhhbbhshbhhhshsbsbhbhhhhhhhhsbsbsbhhhhhsshhhhbbhhhsbhhhhhhshhbsshhhhhhhhhbhbssbbhsbhhhhsbsshbbhhsshhhhbbhhhsbhhsshbhbshhhbhsshhbhhbhhhhhshsbbhhhhhhssbshhbbhhhhhhhhhhsshhhhhbhsbhhshhhhbbshhhhbhsshhhbhbhhhhhsbhhhshbhsbshbhhhhhhhhhhhhsshhhhhhbhbhhshbssbhhhsbhhhshbbhsbhsbhhhhsbhsshhhhhhhbshhhhhbhshhbshhbbsshhhbsbshhhhhhbhbhshhshhhhhhhhhhhhhhhhbbhsshhhbbhhshhbhhshhsbhshhhhbshhhbshbbhhsbhhhhhhhsbsshbhhsbshbbhhhhssbbhhhhhhhhsbhhsshhhhhhhhbhshbsbbhhhhhhhhhsbsbhssbhbhhsshhhbshhhhhhhhhhhbbshhhhshhhbhhhshbshhhhhhhhhbhhshhhbbsbhhhhhhhhsbhhsshhhhhbhbhshshbhhhbhshbhhhhhhhhssbbhhhsbhshbshhshhbshhhhbbsbhhhsbhhhhhhhhhsbhhsshbbsbhsshhhhbhbhshshbbshshhbhbshbsbhsshhbhshhbhshhhhhbbhhshshhbhbhsbhhhhsshbshhhhhhhhhbhbhsbshshhhbshhhhbbhhhsshbhshhbbhhsshhbbhhhhhhsbhshhbhshhhhshbbhhshsbbhhhhsbsbhhhhsbhhhhsbhsshhhhhbhbhhhhhhhsshbbhhhhhhshshbhsbsbbssbhhhshhhhhhhhbhbhhhsshbhbhsshhbshhhhhhhhbsbshhhhhhhhbhshhhhbbhssbbhhhhshhshhhbbhhhhhhhhshhbhhhhshbhhsbhhhhsshbhshhhbshhhbbhhsshhhhhbbhhhhssbshhhhhbbhhhhsshbhhbhhhhhshbhhsshhbshhbhhbhshhhbhhhhhhhhhshbhhsshbbhsbhssbbhhhshhshhbbsshhbhbhhhsshbhbshbsshbsbbhhsbhhhhhhshhbhsshhhhhhbbhsbhsbhshhbhsshhbhbhhshhshhhbbssbshhbbshhbhhhhhshshbshhhhhhhhhhhhhhbbhshhbhhhhhhhsshhbshhhbhsbbhhhhsbshbhshshhhhhbbsshhhbbhhssbbsshhhhbhhhhhbhhsbhssbbshhbhhhsshhbhhhbhsshhhhhhbhbhhhhhhhhhhhhsshhhbshhhbhbhshhhshhhhbbhhhhshhbsbsbhssbhhsbsbshbhbhhshbhhhhhsbhssbhbshbssbbhssbshhbhhshhhhhhbbhhhhhsbshbhhshbhhhhhshhhshbbsshhhbbhsbshhbhhsshhbbhhhsshhhhhhhhhhhhhbhshbshhbbhhhhsshhhhbbsbhhshshhhhbsbhsbbhhhsshbhshhhhbhshbbhhsbhsshhhbhsbbhhsbsbhshshhhbbhssbbhhhhhhhsshhhhhhhhhbhbhhsshhhhbhsbhbhhsshhhbbsbhhsshhbhbhshhbhhhhhshsbshbbsshbshhbshhhhbsbshbsbhbhhshsbhbhsshhhhhhbsbbhsshhhhhbshhhhhbshhhhhbhhshhhhhhhhhbhbhsbhshshhhbbshbhsshhhhbshbhshhhbbhshhshhhhbbhhhshbsshhbbhsshhhhhhhhhhbbsbshhhshbbhshshhbhhshhhhbbhhssbbhshhshhhhhbsbshhhhhhbshbbhhhssbhbhhhhhhhhhsshhhhbhbsbhhhhsshbbhhhhsbhhhhsshhhbhbhhsshhhhhhhhhbbhhsshbshhhhbhshhbhhsbhhhshhhhhhhhhhbbhhsshhhhbhsbbsbhsbhsbhhsbhsbhhhsshhhbhbhsshhbbsbhhhhhssbbhhsshbshhhbbssbbshshhbbshshhhhhhhhbshbbhhshsbbhhhhhsbsshhhhhhbbhshhhbsshhhhhhbhshbbhhhhhhhhhhhhsshhbbhsshhbbhhhssbhbhhhsshhhhhhhhhhhhhbbsshhhhbbhhhhhhsbhhhhssbshhhhhbbhssbbhhhsshbsbhbhhssbbhhhshshhbbhhhssbhshbbhshhsbshhbsbbshbshbsshhhbshhhhhhhhhbbhhhhshhbhsbsshhhbbhhsshhhhbbhhhsshhhhbhbhhsbhhhhhhhhhhhhhhhhsshbbhsbhhhsshhhhhhbbhhhhshhhbhhhsshhhhhbbhhhhhhhhshsbbsbhhhsshhhhhbhshhbbhsshbhbhshshhhbshhhhhbshbshhbhshhbhhhbhhhhshbhhhhshbsshhhbhbhhsbshhhshhhhhhbshhhhhhbshhhhhhbshbbhhhsbhhhssbshbsbbhsshhhhhhhbbhhsshhhbhhhshhhhhhhhhhhhhhhhbbhhsshhhbbshhbhsshbbhhshsbhshhhhhhhhhhbshhhhbsbshbbhshbhhhsshhbhshhhhhhhhbshbbhshsbhhbhhhhhhhshhsbbhshhshhbhshhhhhhbhshhhhbshhhhbsbsbhshhbshbbhhhhhshsbhhhhshbsbbhhhhhsshbshhbshhhhhhhbbshbhhhhssbbsshhbshbbhssbbsbhhhhsbhhhhhhhhhhhsshhhbshhbbhhhhhhsshbbhhhsshbsbshhbhhshbhbhhhhhhhhsbhhsshbhbhhhhhhhhsbhsshhhhhhhhhhhhbbsbhhhsshhhhhbbhhhhsshhhhhhbshbbhshhhbhhsbhhsshhhhhbhshbshhhhbhshbbshhbhhhhsshbhbhhhsshhhhbshhhbhbhhhshhbhhhhshshhhhhbbhssbhhhbhhhhhhhhhhhshbhhhsbhhshhhbhhhhhshhshhbbhhhshhbhhssbhsbbhsshhhbbhhhsbhhhssbhshhhhhhhhhhhhbhshhhhhbshhhhbbhhhsbsshbhbsshhhhhbbhhshshhhhbhsbbhhhhhhhhhsshbhhshbhhshbsbhshhhhhbbhhhhshshbshhhhbshhhhhhhhhhhhhhhhbshhhbshhhhbhbhsbssbshhhhhhhhbbhhshhbhhhsshhhhbbshbhhhhhshhhbsshhhhhhhhhhbshhhhhhhhbhshbshbsbbsshhhhhhhhhhhhhhbbsbhhhhshhshhhbbhsbhhhsbhsshbshhhbhbhhhssbbhhhhhhshbshhhhbsshhbbhhsshbhshhhhhhhhhhhhhhhhhhhbbhsbhhhshbsshbshbhsbhshbhshhhhhhhhbhbhhhhhhhhhssbbhhhsbshhshhhbhhshhhhhhhbbhhhhhhhsshhbbhhhhhssbbhhhsbhhssbbhhhhhhhhhshbshsbhsbhhbhhssbbhhsbhhhhhhhsshhhhbshhhhhhbshhbhshhhbbhsbhhhhhhhhhhhhhsshhhbbshbhhshbhhhhsshhhhbbshbhhhshsbsbshbhhbhhhhhhhhhhhhhhhhhhsshhhbhbshbhhhshhbhhhhsshbbhhhshbhhhhhhhhhhhhsshbhhhshhhhhhbbhhhsshhhhhbhhbhsbshhshhhhbhshhbbsshhbbhhhhhhhhsshhhhhbhbsbhhsshhbbhhhhhsbsshhhhhhhhbshhbhhhbhshbhshsbbsshhhhbbhhhhhhshshbbhhhshshhhhhhhhhhhhhhhhhhbbhsbhsbhhhshbhhhhhhhhhhhhsshhhhhhbshhbsbshhbshhbhshhhhbhbsbhhhsshhhbsbbhsbsbhshhshhhbbhhhhhsshhhbhsbshhhhbbhhsshbbhhsbhssbshbshhbhhhbhhssbbsshbhsbshhhhhhhbshhbhbhhhhhshhshhhhhhhhbhbhhsbsbsshhhbbhsshhhhbbhhsshhbbhhhhshhbsshhhhbbshhshbsbhbhsshhhhbbhhhssbhbshbhhshshhbbhhshbhhhhsbhhhhhhsshhhhhhbhbhhsshhhhbbhhhhhhhhhshbhhshbhhhhhhshsbbhhsbhsshhbbhsshhhbbhhsshhhhhbhhbhhshsbbhhsshhhhbshhbbhsshbbhsshhhhbbhhhhhhhhhhhhshshbbhhhsshhbbhhhhhhhhhshshhhhbbhhhhhsshhhhbbhhhhsshbshbshbbhhhsshhhbshhbbsshhbbsshhhhbhshhbshbhbsbhhsshhbbsbhhssbbhhhhhhssbhhbhhhhhsshbbhhhshhbsbhhhshbhhhhhsshhhhbhshbbhhhhhhhhhhhhhhhhhhhhshbshbhhhshbhsshhhbhsbshhhhhhbbshshhbhshbhshbhsbsbhhbhhhhhhssbhsbhbhhhhhhhhhhhhhhhhhhhhhhsshhhhhhbsbbhssbbhhsshhhhhhhhhbshbbhhhshshhbshhhhhhbhshhhbbhhhhhhsshhhhhhhbhbhhhsshhbsbbhhhhshhsbsbbhsshbbhhhhhhhhhhhhsbsshhhhhhhhhhhhhhbbhhhsshbshbshhhhhbshhbsbbhsbhsshbhbhssbbhhhhhhshhshbhbhhhhshbhhhhssbbsshhhhbbsbhhhhshshhhhhhhhhhhhhhbbshbhsshhhhbbhshbhhhhsshhhbshhbsbbhhhshshhhbbhshbhshbhhhsshhhhhhhbbhshshhbbhsshbhhbhsshhhhhbhsbsbhshhhhhhhbhshhhbhshhbsbshhhbbhsshbshhhhhbbhhhhhhhshbhhhshbssbhbhshsbshbhbhhshhhsbhshbbhsbhhhhsbsbhhhhhhhsbhhshbhhshhbsshhbhbhshbhhhhhhhhhhhhssbhshhbbhsshhhhhbbhhssbshhhbhshbbhhhsshhbbhhhhhhhsbsshhhhhhbhbhhhhhhsbhhhhhhshhshhhbbhshbhhhhssbbhhssbbhhhhhsbsshhbbhhhhsshhbbhsshhhhhhbbhhhhshbhsbhhhhhhhshshhhhbsbhhhshhhbbhhhhhhhsshhhbhhbhsbhhhshhbhhhsbhhhsbhhsbhsbhhhhhshbsshhhhbbhshshhbhbsshbhbhhsshhhhhhhbhhbhhhhhssbbhsshhhbshhhhbbsshbbhhhsshhhhhhhhhhhhbbhhhhhshbhsshhhhbbhhhshshhhbbhhsshhhbbhhhhhhhhhhhhhshhhbhhhhhsshbbshshhhhbhbsshbbhhhhhsshbbhhhhhshshhbbhshbhhsbhhhsshhbshhhhhbbhhhhhhsshhhhhbbhhsshbhshhbhbhhhhsshbhhshhbhbhhhhssbhhbhhhshhbhhsbhsshhbbhhhhhsshhbshhhhhhbhhshhhhbbhhhsshhbhshhhhbshhhbsbbhhshshhhhhhbshhhbhhshhhhbhshhhbbhhhhhhhhhhshhshhhhhhhhhbbhhhssbhhhbhshshhbhhhhshbbhshbhhshhbsshbshbhbsbhhhhhhhhsshbhhbshbhhhhsbhhhshbhsshhhhhbshhhhbbshbhhsbsbsshbshhhbbhsshhhbbhhhhssbbhhhhhhsshhhhhhbbhhhsbhshshhhhhhbhhsbbhssbbhhsbhshbsshhhbbhhhhhhhhhhhhsshbhhshhbbshshbhshbsbhbhshsbbhhhhsshbbhhshhbhhhhsbhhhhsshbbhhhsshhbhhbhhshhbsbhshhbhhsshhhbbhsshbshhhhbhshhhbbhhhhhhhhsshhbbhhhhsshhbbhhsshhbshhhbshhbbhsbhhhshbsshbbhhhhhsshhhhhbshhhhhhbbhhhhhhsbsbhhhshbhhssbbhhhhssbbhhhshsbhbhhhhhhssbbhsbhhhhhhsshbbhhsshhhhhhhhbhshbhsbhbhhsbhhsshbbsbhhhhhhsbhhshshbhhbhhshbhsshhhhbbhsbhsshhhhbbshhbhhhhhhshbsbhhhshsbbhhsbhhhhhsbhssbbhsshhhbbhhhhsbhhhhhhhhhsbhhhhhhhhhhhsbhhhhssbhsbbhhsbhhshsbhshbbhshbsshhhbshhhhhhbhshhhhhbshhbshhbhhshbbhhhsbhsbsshbhhbhhshbsbhhssbbhhhhssbbhhhhsshhhhhhbbsshhbbhhsshhhbbhhsbhhsshhhhhhbsbhhhhbhhshbshbsbhhhhsbhhsbhsshhhbshbbhhhhhhshbhhhsbhsbhhhhhsshhhhhhhhbshhhbbhsshhhhhhhhhbbhsshhbhbhhhhhhhshhhshhhbhhbhhshshbbhshbshbhhhhhhhsbhhhhhhhhhhsbhhsshhhhhbhshbbhhhhhhsshhhhhhhhhhhbsbshhhhhhhbbhsbhsbhhhhhhhhhssbbhsbhhhhsshhbshhhhhbhhhhshhbsbshhhbshhhbshhbhhbsshhbhshhhbhhbhshshhhbsbhbhssbbhsbhhhhhshsbshbbhsshbhshbbhsbhsshbshhbbhhhhhshshhhhhhbbsshhhbhshbshbbhhshbhshbhhhhhhhsshhhhhhhbhshhhhbsbbhhhhsshbbhsshhhbbhhhhhsshhbhsbhshhhbhhbhhsshhhhhbhbhhshshbbhhssbhbsbhsshhhhhhhbbsshbbhhhhhsshbshhhhbbsbsshhbbhhhsbhssbshhbshbbhsshhhhbbsshbsbsbbhhhshbhhhhhsshhhhhbbhhhhshbhsbhhshshhhhhbhhbhhhsbhsbhsbsshbhhhhhhbsshhbbhhshhshhhbbshshhhhhhhhbbsshhbhbssbsbbsshhhhbshbshhhbbhssbsbbhshbhhhhhhhhshhhbshbhhhhsshhhhhhhbhshbbhhhsshbhbhhhhsshhhhbhhbhhhhsbhhhhhsshhbshhhhbbhsbhhshshhbbhsbhhhhhhsbhsshbbhshhbsshhhhhhbbhhhhhsbhhsshhhhhhbbshsbsbhbhhhhhhsbhhhshhhshbhshhhhhbbhhhsshhhbbhhhhssbbhhhhsshhbshbbhhhsbhsshhhhbbhhhhsbsbhhhsshhbhshbhbhhhhsshhhhbhhbssbshhhhhhhhbhhbhhsshbbhhhhhsshhhbsbshhbhhsbshbbhsshhhhhbbhhsbhsshhhbshhhhbsbbsshhhhhhbshhhbhbhhshshbbsshbhsbshhbbsshbbhshshbhbssbbhhhhssbhbhhhhhshbhsbhhsbhssbbhshbhsbshhbhhhsshhhhhhhhhhhbhbhhhhhssbbhshbhhhshhshhhbhhbhhhhhhhhhhhssbbhsbsbhhhhsshhhhhhbshhhhbhhbshshhbhbsshhbbhhsbhhhhhshshbhbhhhhhhhhhshbsshbbhsbhhhhhshshhbbhsshhbbhssbbhhhhhshbhshshhhbbsshhbbhsshhhhbbhhhhsbhhhhhshsbhsbhbhhhsbhhsshhhhhhhhhhbbsshbshhhhhhhhbhbhhhhsshhbbhsshhbhhhshhbshbshbbhshshhhbhsbbshbshshhhhhhhhhhhhbbhhsbhhhhhhsbhhshhbhsshbshhhhhhhbbssbbshbhhshbhsbhhhsbhhshbsshbhshhhhbshbhhhbshshhhhhhhhhbbshbshshhhhbhhbsbhsshhhbbhhshhhshbhshhhhhhhhhbbhhssbbhshbhhhhhshsbhhshbhhshhhhhbbhssbhshbshhbhbsshhhhbbhsbhshbhshbhhsshbhhhbhsshhhbbhshshbbhhhsbhhhsbhhhsshbhshbhbhsshbshhhhhhhhhhhhbbsshhhhhbbhhsshhhbshhbbhhhhhhhsbhhhhhsshbbhshhbhhsshbhbhhhhhhhhhsshhhhhbhshbsbshhhhhhhhbhsbhshbbhhhhhhhhhhsbhhhshbhhhhsbhshbhhsshhhhhhhhbbhsbhhhsbhssbbsshhhhbbhsshbhshbbhssbhshbshhhbbhhhsbhhhhhhsshhhhhbbhhhhssbhbshbhhhhhsshhbhshhbhsbbhhhhsbhssbhhhshhhbhbsshhbhbsshhhhbshhbhshhbbhsshbbhsshbbhhhshbhhssbshhhbbsshbhbshbhhhhhhhhhhhhsshhhhhhhhhbbhhsshhhhbshhhhhhbbhhhhhhhhhhhhhhsbhhsshhbhshhbbhhhhshbhhhhhhhhsshhbhbhhhhshhbhsshbbhhhhhhhhhhhhshbshhhhshhhhhhhhhhhhbbsbhhhhhshsbhsbhhsbbsshhbbhshshhhhhhhhbbhhshbhsbssbhhhsbbhhsshhhhhhbhshhhhhhhhbshhhbbhhsbshhhbshshhhhhhhhhbbhhhhsbhhhhsshhhhhhhhhhhhhhhbhshhhhbshbshhhbhsbbhhhhsshhhhhbbsbsshhhbshhhhbshhhbhsbbshhbhhhhhhhhhsbhssbbhhhhhshbhhhhsbhsshhhbbhsshhbhsbhbhhshbhhhshhshhhbbhhhsshhbshhhhhhhhhhbshhbbhhshhshhhbhshhhhhhhhhhbsbsbbh"


COCONUT_TRADES = "bhhshhhhhhsshhhhhhhhhhhhhhhhhhhbbbhhhhhshbbhhhhshsshhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhbbbhhhhhhhhhhhhhhshhhhbhhhhhhhhhhhhhhhhsshshhhhhhbbhhhshhbbhhhhhhhhhhhhhshhhbhhhhhsshhhsshhhbhhhhhhhshhhhbhbhhhhhhhhhshbhhbbhhshhbhshhhhhhhhhbhhhshhhbhshhbhhhhhhhhhhhhsssshhhhbhhhshhhhhhhhhhhbbbbhhhhhhhhhhshhbhhhhhhhshshhhhhhhsshhhhhhhhbbhbbhhhhhhhhhhhhhhhhhhhhhhhhhsssshhhhhbhshhhhhhhhhhhhhhhhhhhhhbhhhhhshhhhbhhhhhbbhhshhhhhbhbhhhsssshhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhshshhhhhbbbhhhhhhhhshhbhhhhhsssshhhhhhhhhhhhhbbhhhsshhhhhhhhhbhbhsshhhbbbhhhhshhbhshsshhhhhhhbshhhhhhhhhhhhhbhhhbhhshhshhhhhhhbhbhhhshbbhhssshhhhhhhhhhhhhhhhhbhhhhhhhbbbhssshhhhshhhbhhhhhhhhshhhhhhhhhbbhshhshhhhhhhhbbbbhhhhhhhhhhhhhhhshshsshhhhhhhhhhhhbbhhhhhhhsshhhhhhhbbbbhhhhhhhhhhhsssshhhhhhhhhbhhhhhhshhhhhhhhhhhhhhhbhbhhhbhhbhhhssshhhshhhhhhhhhhhhhhbhbshhhhhhhhhhbhbbhhhhshhhhhhsshhshhhhhhhhhhbhhhhhhhhhhbbbhhhhhhshhsshshhbbhbhhhbhhhhhhhhhhhhhhhhhhshssshhhhhhhhhhhhhhhhhhhhhhhhbhhbbhsshshhbhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshbhhhshssshhhbshbhhhbhbbhhhhhhhhhhsshshbshhshhhhhbbhbbhshhhsshshhhhhhhhhhhhhhhhhbhbhsshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhhhhbbhhhhhhshshbbhhsshhbbhhhhhhshhhhssshhhbhshhhhhhhhhhhhhhhhhhhhbbbhhshsshhhhhhhhhhhhhhhhhhhhhhhbhhhhhbbbhhhhhhhhsshsshhhhhhbbbbshhhhshsshhhhhhhhhhhbbhbhhhhshhshhbbsshshbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhssbbhhhhhhhhhhhhhhhhhhhssshhhhbbbhhhhhhhhhhhhhhhhshhbhhshhbhhhhhhhhhhsshhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhssshshhhhhbhhhbbbhhhhhsssshhhhhhhhhbhhhhhshhhbhbbbhhhhhhsssshhhhhhhhbhhhshhhhhhhhhhhbbhhbhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsssshhhhbbhhhhhhhhbhhsshhbhhhhhhhshbbbhhhhhhhhhhhhhhhhshhshhbbhhhhhhhhhhhhhhhhhhhhhhsssshhhhhhbbbbhsshhhhhbbhhhhhhhhhhssshshhbbhhhbbhhhsshhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshshhhhshhhshbhhhhbbhhhhbhhhhhhhhhhhhhhhhhhhhhsbhhhhhhhhhhhhshssshhbhhhshhhhhbbbbhhhhhshshshshhhhhhhbbbbhhssshhbhhbhbhhhhshhhhhhhhshshhhhbhhhshhhhbbhhshhhhhhhhhhhhhhhbhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhbhsshbshhbbhhhhhhhhhsshshhhhhhhhhhbhbbhhhsssshhhhhhhhhhhhhhhhhbhbhhbbhhhssshshhhhhhhhhbbhhhhhhhhhhhhbbhhhhhhsshshshhhhhhhhhhhhhbbbbhhhhhhhsssshhhhhhbhshhhhhhhhbhhshhhhhbhhhshhhhhhhbhhhbhhhhhhbbhhhhshhshhhhbhbhhhshssshhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhbhhbbhhhhhhhhhhhhhhshhhsshhhhhhbhhhhhhhhsbbhhhhhsshbbbhhhhhhhhhhhsssshhhhhhhhhbbhbbhhsssshhhhhhhhhbhhhhhshhhhhhhhhhbbbhhhhhssshhhbhhhhshhhhhbshhhhhhhhbhbhhbbhhhhhhhhhhhhhhhhhhhhhshshbbhhhhhhhhhsssshhhhhhhhhhhbbbhhbhhshshhhhhhbhhhhhshhsshhbbbbhhhhhhhsshhhhbhbhhhhsssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbshhhhhhhhhhhhbhhhshhhhhhhhhhhhhhbshhhhhhbhbbhhhssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhbhhhhhhhhbbhhhhhshhhbhhhshhbhhhhhhhhhhhsssshhhhhhhhhhhhhhhhbhhbhhshhhhhhhhshhhhhhhhhhhhhhhhhbhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhsshhhhhhhhhhhbbbbhshhhbhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhhhhhshhhbbbhhshshsshhhhhhhbbhhhsshhhhbhhhhbbhhhhbhshsshhhhbhhhhhbhbhhhhhhhhhhhhhsssshhhhhhhhhbbhhhhsshhhhhhbhbbbhhhhhhhhhhhhhhhhhhhhhshhbhhhhhhhhhhhsbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshhhshhhshbhbbbhhhhhhshhssshhhhhhhhhbhhshhhhhhhhbbsshhhhhhhbbbhhbhhhhhhhhhhhhhsshhhhbbhhhhhhsshhshhshbhhhhshhhhhhhhhhhhhhhhbbhbbhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhbhhhhhhhhhhshhbhhhhhhhhhsshhhhbbhhhhhhhhhhhsshhhhhshhshhhhbbbbhhhhhhhhhhhhhhhhhhhhhhshhhhhhsshhhhhhhhhshbhhshhhhhhhhhhhhhhbhbhhhhhshhhbhhhbhhhbhhhhshsshhhshhhhhhhhhhhbhhbhbbhhhhhhshhbhhhhhhhhhhhhhshhhhshhbhbhhhhhhhhhhhhhhhshhhhhbhhshhhbhsshhhhshhhhshhhhhhhhhhhhhhhbbbbhhhhhhhhhhhhhhhshsshbhhhsshhhhhhhhhbhhhbhhhhsshhhhhbhshhhhhhhhhbhhhhhhhhhhhshhhhhhhhhhhhhhhhhhbbbbhhhsshhshhhhshhhhbbhhbhhhhhhhhhbsshhsshhhhhhhhhhhbbbbhsshsshhhhhhbbbhhhhhhhhhsshshhhhbbbhbhhhhhhhsssshbhshhhhhhhhhhhhhhhhbbbbhhhhsshhsshhhhhbhbhhbhshhbhbhshssshhhhhhhhbhhhhhhhbbhhhhbhhhhhhhhhhhhhhhhsshhsshhbhhshhhhhhhhhhhbhshhhhbbhhhhhbbhhhhhhhhhhhhhhhhhhhsssshhhhhhhhhhbbhshshbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhshhshhhbhhbbhhhhhhshhshbhhhshsshhhhhhbbbbhhhhhhhhhhshhhhssshhhhhhhbhhhhbhhbbhhhhhhhhshshbbhhhhhhshhhsshbhbhbhhhhhhhhhhhsbhhssshbhshhhhhshhhhhhhhhhhhhbhhhshhhhhhhbhhhbhbbhhhhhhhhhhhhhhhhhhhhhhshsshhhbhhbbhhhhhshhhhhshshhbbhsshhbbbhhhhsshhshshhhhhbhshhhhhhhhhhhhhhhhhhhhhhhhbhhhshhhbbhhhhhbhhhshhhsshhhhhhhhhhhhhhhbbhhhhsshhhhhhbbbhbhhhhshhhshhhhhhhhhhbbhhhsshsshhhhhhhhhhbhshhhhbbbbhshsshhhhshhhhhhhhhhhhhbbbhhbhhhhhhhssshhbbbhhhhhsshhhhhshhshhbbhhhshhhshhhhhhhbhhbhhhhhbbhhssshhshhbhhhhhbhbhhhhhshhshshhhhhbhbbbhhhhhhhhhhhhhhhhhhhhshbhhhhhhhshhbhhhhhhhhhhhhhhhhhssshbbbhhhhhhhhhhshhbhhhhssshhhbhbhbhhhhhhshhhhhhhshshhhbhshshbhbhhhsshhhhhhhhhhhhhhhhhhbbbhhbhhhhhhhhhhhhhhhshhhhhhhshhhhhhhbbhssshbhhhbbhhshhsshhhhhshhhhhhbbbhhbhhhssshbbhhshhsshhhhhhhhhhhhhhhbbhhbbhhhhhhhshhhhshhhhhhhhhhhsshhhhhhhhhhhhhhhhhhhhhhbbhbhhhhhhhhssshhbhhbbbhhhhhhhhhhhhsshhhhshhhbbbhhhhhhhhhhsshshhhbhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhbhhhhhhhhhhshbhshhhbhhhhhhhhhhhhhhsshhshhbbbhshhhhhbhhsssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbhhhhbhhhhhhhhhhhhhhhhhhhsshhhhhhhhhshshhhhhhhbhbbhhhhsbbhhhhhhhhhhhhhsssshhhhhbhhbbhhhhhssshhhhhhhhhhhbbbbhhhhhhhhhhhhhhhhhhhhhshhhhhbsssshhhhhhhhhhhhhhhbhbhhhhhhhhhhhhbbhhhhhshhshhhhhhhhbhbhhhhhhsshhhhbbhhhhssshhhhshhhhhhhhhbbbhhhhhhbhhhsshsshhhbbhbbhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhbhhhhhhshhhhhhhhhhhhhhhhhbbbbhhhhhsbhhhhhshhshbhhhhhssbhbbhhhhhhhhhhhhhhhhhhhhsssshhhhhhhbbhhhshshbshhhhbbhhhhbbhhhhhhhhhhhhhhhhsshhhhhhbbhhhshhhshhhhhbhhhbhhhhhsshhshhshhhhhhhhhhbbbbhhsssshhhhhhhhhhhhhhhhhhhhhhhhhbbbhhbhhhhhhhhhhhhhhhhshbhhhhhhhhhhhhhhhhhhhhhhhhhhhhshbhhhhhhhhhhhhhhshhhhhbhhhhhhhhhhhhhhhssshhhshhbbhbhbhhhhhhhhshshhhshhbhbhhhhssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhbbbssshhhhhhhbbhhsshhhshhhhhhbbhbbhhhhhhhhhhhhhhshssshhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhshhsshhhhhhhhhhbhhhbhbhhhhhhhhhhhshbhhhhhhshhshhhhhhhbbhhhhhhhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhhhhbhshhhhhhhbhbbbhhhhssshhhhbhhshhhhbhbhshsshhhhbbhbhhhhsshshhhhhhhbbbbhhhhhshbhhsssshhhhhbhshbbbshhbhhhssshhhhhhhhhhhhhhhbbhhshhhhbhhshshhbhhbhhbbhhhhhhhssshhhbhbbhhhhsshhhsshhhhbbshhbhsshhhhhhhhhhhhbhhhbbhssshhhhhhhhhhhhhhhbhshhhhhhhhhhhhhhhhhhhhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhssshshbhhhbbhbhhhshhhhhhbhhhhhhhhhhhhhsshshshhbhbbbhhhhhhhhhhhssshhhhhbhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshbhhhhbhhhhhhhhhsshsshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhbbhhhhhshhhhhhhhhhhbhhhbbhhhhhhhhhhhhhhhhhhhhhhshhhhhssshhbshhhhhhhhhhhhhhbhhshhhhhhbhhshhhhhhhhbbbhhbhhhhhssssbhshhhhhhhhhhhhhhhhhhhhhhhhhhbbbhsshbhhbbhhssshhhhbbhhbhhshhssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhbhhbbhhshssshhhhhhbhbbbhhhhhhhhhhhhsssshhhbhhhhhbbhbhhhhhhhhhhhsshhbhbhhhshhhhhbhhhhshhssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhhbbhhhhhhhshsshhhhshhhhbbbhhbhhhhhhhhhhhhhhshhhssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhbbhhhbhhhhshsshhhhbbhhhhsshshbhbshhhhhshhhhhhhhhhhhhbhhhhshhhhhhhhbbbbhhhhsshhhhbhhhhhhhhhhbhhhhhhhhhhhhhssshhbhhhbbhhhhhhsshhbbhhhhhhshhhhbhhhhhsshhhhhshhhbbbhhhhhhhhhhhhhhhhhhhhhsshbbhhhsssshhhhbhhhhshhhhhhhhhhhhhbbbbhhhhhhhhhhhshhhbhhhhhhhhssshhhbbhbhhhhsshhhhshbhhhhhhhhsshhbhhhhhhhbhhhbhhhhhhhhhhhsshbbhshhhbbhhhhshhsshhhhhhhhhbhbbhhshhhhhssshhhhhhhhhhbhhhshhhhhhhhhhhhhhhhbbbhbhhhshhhhhhssbbbhhhhhhhhhhhhhshhhhssshbhhbbhbhhhhhhssbbhhhhhhshhbhhshhhhhbhhhhhhhhhhhhhhhhhhhhhhhhshbhshhhhsshbhbbhhhhhhsssshhbbhbhhhhhhhhshhhhbbhhhhhhhhhshbhhhhhhhhhhhhhshhhhhhhhhhhhbhhhhhhsshhsshhhhhbhhhbhhhhhhhhbhbhhhsssshbhbhhhbbhhhhhhhhhhshhhhssshhhhhhhhbhhhhhhhhhbhhhhbbhshshhhhhhbbhhhhhhhhhhhshssshhhhbhhhhhshhbbhhbbhhhshbhhhhhhhhshbhhhhhhhhhhhhhhhhhhhhhshhshhhbbhhhhhhhshhhhhshsshhbhhhhshhhhbhhhhbhhhhhbhhhbhhhhhhhhhhhhhhhhhhhshssshhhhhhhhhbhhbbbhhhssshhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhbbbhhhhhhhhhhhhsshbhhshshhhhhbhhhsshhhhhhhbbbbhhhhhhhhhhhhhhhhhhhhsbhhhhhhhhhhhhhhshhhhssshhhhhhhbbbbhhhhhshhhhhshhhsshhhhhhhhhhhhbbbbhhhhhhhhhhhhhsshhhhshhbhhshhshhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbbhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhhhhbhhhshhhhbbhhbhhhbhhsssshhhhbbbhhssshhhbhhhhhhhhhhhhhhshhhhhbhhshhbhhbbhhhssshhhhhhhhhhhbhhshhhhhhhbhhhhhhshhhhhhhhhbbbbhhhhsshhhhhhhhhhhbbhhshsshshhhbbhhsshhhhbhhhhhhhbhsshbhhhhhhhhhbbbhhhhhhhhhshsshhhhhshhhbbbbhhhshhshhbbhhhhhhhhhhsbhhhhhhhsssshhhhhhhhhhhhhhhhhbhhhbhhbbhhhhhsbhhhhhhhhhssshshhhhhhhhhhhhhbbhhhhsshhhhhhhhhhbhbhsshhhhhhhbbhhhhhhsshhhhbhbshhhhshhbbhhhsshhhhhhhhbhhhhshhhhbhbbbhhhhhhhhhhhhhsshhbhhhshhhhhhhhhshhshhhhhhhhhhhhhhhbbhhhbbhshhhhbhssbbshssshhhhhbhhshhhhhhhhhhhhhhhhhbhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhshshhhhhsshhhhbhbbbhhhhhhhhhhhhhhsssshhhhhhhbbbhhhhhhbhhshshhbhsshhhhbhsshbhhsbbhhsbbbhhhhhhhhhhshhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsssshhbbhbbhhhhhhhhhhhhhhhhhhshhhhbhhhhhhhhhhhhshshhhhhhhshhbhhhhhhhhhhhhhhhbhhhshbbhhhhhhhhhhhhhhhhhhhhshhhhhhbhhhhhshhhsshhhshhhhhhhhhhhhhhhhbbhhbbhhshhhhhhhshhhshhhbhhbhhhbhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhhhbbbbhhhhhhhhhshhhhhshbhsshhhhhhhhhhhhshhhhhhhbbhhbhhhsshbbhshhbbhhhhhhssshhhsbhbhhbhbhhhhhhhhhhhhhshhssshhhhhhhhhhhhbhhhhhhbbhhbhhhhsssshhhhhbbhhhshhbhhhhhhhhshhshhhhbbbbhhhhhhhhhhhhhssshshbbbhbhhhhhhhhhsshhhshhhbhhhbbhhhhhhhhhhssshshhhhhhhhhhhhhhhbbhhhhhhbbhhhhhhhhshhhhhshhhhsshhhhhhhhhhbhhhhhhsbhhbhhhhhhbbhhhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhbbbhhsbbhhhhhhhhhhhhhhhhhhshshshhhhbbhhhhhhhssshhhhhhhhhhhhhhhhhhhhhbbhhhhhsshhhhhhhhhhhhhhhhhbbbhhhhhbhhhhhhhhshssshhhhhhhhhhbhhhhbbhbhhhshshhhbbhhhhhhhhhhhhhhsshhshhbbbhshhbhhhhhhhsbhhhshhhhssshhhhhhbhhhbbhhbhshhsshshhhhhhbbbbhhhhhhhhhhhhhhhhhhshhbhhhhhhhhhhhhhhhhhhhhhhhhshbhhhssshhhhhhhhhhhhhshhhhhhhhbhhhhbbhhbhhhhhhhssshhhhhbbhshshbhhhhhshhbbbhhhhhhhhhhsssshhhbbhhhhhhhhhbbhhhhhhhshhbhhhhhsshshhhshhbbhhhhhsshhhhhhhhhhhhhbhbbbhhhhhhhhhhhhhhshshhhsshhhhhhbbbbhhhhhhshsshhhhhbbbhhhhhhhhsssshhhhhhhhhhhhhhhhhhhbhbhbhhhhhbhhhsssshhhhhhhhhhhhhhhhhhbhhhbbbhhhsssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhbbbhhhhhhhhhhhhhhhhshshsshhhhhhhhhhhhhhhhhhhbhhshhhhhhbbhbhhhhhhhhhhhssshhhhhhhhhbhhhhshhhhhhhhhhbbhhhhhhhhhhsshhhhhhhhhhbhbbhbhhhhhhhhhhhhhhhsshshhhhbhhbhshbbhhhhhhhsshhhhhhbbhhhhhsshbhhhhhhsshhhbhbbhhhhhhhhhhhhhshhhbhhhhhhhhhhshhhhhhssshhhbhshhhhhhhhhhhbhhbbbhhhsbhhshssshhhhhhhhhhhhhhbhhhshhhhbhhhshhhhhhhbbhbbhhhhhhhhhhhhhhhshshhhbhhhhhhhhhhbhhhhhhhhhhhhhshhhhshhhhhbhhhbhhhhhhhhhshhhssshhhhhhhhhhhhhhbhbhhhhhhhhhhhhhhhhhhhhhhhhbbhsh"

COCONUT_COUPON_TRADES = "sssssssssssssshshhhshhhhhhhhhbhbbbbhbbhhhbbbhhssssshshssshhhshhhhhhhhbbbbbbbbbbhhbbbbbbbbbbbbbbbbbbbbbbhhhhhhhhhhhhhhhhhhhhhhhhshhhhsssshhhhhhbbbhhshbbbhhhhhhhhhhhhhshhhhhhhhhsshhssshhhbhhhhhhhhhhhhbhbhhhhhhhhhhhbhhbbhhshhbhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhsssssshsshhhhhshhhhhbhbbbbbbbbbhhhhhhhhhshhhhhhhhhhsssshhshhssshhhhbbhbbbbbbbhhhhhhhhhhhhhhshhhhhhhhsssssssssssssssssshssssssssshhhshhhhhhhsshhhbbbbbbbbbbbhbbbbbbbbbbhhhhhhhhbbbbbbbbbhhhbhhhhhhhhhhhhhhhhhhhhhsshsssshshhhhsbhhhsshhhshssshsssssssssssshhhhhhsshshhhhsssshhhhhhhhhhhhhhhhhbbbhhhhshhbhshsshhhhhhhhhhhhhhhhhhhhhhbhhhbhhshhshhhhhhhbhbhhhhhhhhhhsshhhhhhhhhhhhhhhhhbhhhhhhhbbhhshshhhhshhhbhhhhhhhhhhhhhhhhbbbbbbbbbbbbbbbbbbbbbbhhhhhhhsssshssssssssshhhhhhhhhhhhhhhhhhhhshhhhhhhhbbbbbbhhhhhhhssssssssshhhhhhhhsshsssshhhhhhhhbhhhhhbhbhhhbhhbbshssshhhsshhhhhhhhhhhhhbhbhhhhhhhhhhhbbbbbbhhhhhhhhhsshhhhhhbbbbbbbbbbbbbbbbbbbbbbbbbbhshhsshshhbbhbhhhbhhhhhssshshshhhhssssssssssssssssssshsshhhsshshhbhhbbhhhhhbbbbbbbbbhbbbbhbhhhhhhhhhhhbbbhhbhhhhhbhbhshsssshhhshhhhhhhhhhsssssssssssssshsssssshhhbbhbhhhhhhsshshhhhhhhhhhhhhhhhhbhbhsshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhbbbbbbbbbbbbbbhhhhhshshhbhssssshhshhhshssshhsssshhhhhhhhhhhhhhhhhhhhhhhhhbbbhhshsshhhhhhhhhhhhhhhhhhhhhbbbbbbbbbbbbbbbbhhsssssshhhhbbbbbbhhhhhshshhhhhhhbhhbhbbhbbbhhhhhhhbbbhhhhbbbbbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshshhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshhhhhbbhhhhhhhhhhshhhhhhssssssssssssssssshhhhhhhsssssssssssssshhhhbhhhhhshhhbbbbbhhhhhhssssshhhhhhhhhhhhhhhbhhhbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbhhhhhhhhhssssssshhhhbbhhhhhhhhbhhhhhhbhhhhhhhhhbbbhhhhhhhhhhhhhhhhshhshhbbhhhhhhhhhhhhhhhhhshsssssssshhhhhbbbbhhhhhhbhbbbbhhsssssssssssshbbbbbbbbbbhshhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhshshhssshhhshbbhhbbbhhhhbhbhhhhhhhhhhhhhhhhhhhshhhsshhhsssssssssssshsssssshhhhhbhshhsssssssssshbhbbbbbbbbbbhhbbbbbbbbbbhhhhhhhhhhhhhhhhhhbhhhhhhhhbbhhhhhbhhhhhhhhhhbbbhhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshbhhhbhhhhhhhhhssssssssssssssshshhsssssssssssssshhhshhhhhhbhbhhbhhhhssshshhhhhhhhbbbbbhhhhhhhbbbbbhhshhsssssssshhhhhhshhhhhbbbhhhhhhhhhssshhhhhhbhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhbhhhbhbbhbhbbhbbhhhhsshhhhhbhshshsssssshhhhhhhhhhhhhhhbhhbbbhhhhhhbbhbbbbhhhhbhbbhhhhhhhhhhhhhhhbbbbhhhhbbhhbbbhhhhhhbbbbbhssssssssssssssssssssssbhshhhhsssshhhshhhhhhhhhhhhhhhhhhhhhhbbbhhhhhssshhhbbhhhhhhbbbbhbbbbbbbbbbbbbbbbbbbbbbbbbbhhhhhhhhhhshshbbhhhhhhhhsssssssshhhhhhhhbbbhbbhhhhhhhhhhhhhhhhhhhhhhhhhbbbhhhhhsssssssshshssssssssssssshhhhhhhshssssshhhhhsshsshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbbhhhsssshhhhhhhhhhhhhhhhhhhhhbbbbbbhbbbbbbbbbbbbbbbbbbbbbbhhhhhbbbhhhhhhhhhssssssssssssssssshhssssshhhhhhhhsssshsshhhssshhhhhhhhhhhhhhhhbhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhsshhhhhhhbbbbbbbbbbbbbbbbbhhshhhhsssssssssssssssshhhhhhhhhhhhhhhhhhhhbhbhhhbbhbbbbbbbhhbbbbbhhshshsshhhhhhhbbbbhshhbhbbbbbbbbbbhhbbhhsshhhbbhhhhhbbbbhhhhhhhhshhhsssshhhhhhhhhbbhhhhshhhhhhhbhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhssshssssssssssshhhhhhsssssssssssssshsshshhhhshhhhhhhhbbsshhhhhbbbbbbbbbbhhhhhhbbhbhhshhhhbhhhhhhhsshhshhshbhbhhhbbhhbbbbbbhbbbbbbbbbbbbhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshhhhbbhhhhhhhhshhsshhshsshhshhhbbbbbbhbhhhhhhhhhhhhssssssssssssssssssssssssssshssssshhhhhhhhhhhhbhbbbhhhhbhhbbhbbhhhbhhbhsssshhhshhhhhhbbbbbbbbbbbbbbbbbbhbbbbbbbhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshsshhhhssssshsssssssssshsssshhhhhhbhhhhhhbbbbbbhhbhhhhssssssssssshssssssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhshhhhhhhhhhhhhhhhhhbbbbbhhsshhshhhhsshhhbbhhbhhhhhhhhhbsshhsshhhhhhhhhhbbbbbbhhbshhhhhhhbbbhhhhbbhhhhhhhhhbbbbbbbhhhhhhsssssshsssssssshhhhhhhhhhhbbbhhhhsssssshshhbbbbbbbbhbbbbbbhhshhhhhhhhbbbbbbhbbbbbbbhbbbbbbhhhhhhhhhsshsssssshshhsshhhshshhhhhbhhhhhbbbbbbbbbbbbhhhhhhhhhhhhhssshsssssshhhshhhhbbhhhhhbbbbbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhshhshhhbhhbbhhhhhhshhshhhhhssshhhhhhhbbbbhbhhhhshsssssssssssshhhbhbbbbbbbbbbbbhhhhhhhhhhhhhhhhhhshhssshbhbhbhhhhhhssssssssssssssssssssssssssssshhshhhbbbbhbhhbbbbbbbbbbbbbhbhhbbbhhbbbbbbbbhhhhhhsshhhbhhhbhhhhhshsssssssshhhsssshhhhhssssssssssssssshhssshhhhhhhhhhhhhhhhhhhhhhbhhhshhhbbhhhhhhhhhshhhshhhhhhhhhhhhhhhbbbhhhhsshhhhhhbbbhbbhhhhhhhshhhhhhhhhhbbhhhsssssshhhhhhhhhbhshhhhbbbhhhhsshhhhshshhhhhhhhbbbbbbbbbbhbbbhhssshhbbhhhhhhsshhhhhshhshhhhhhhshhhshhhhhbbbbbbbbhhbbbhhhssshshhbbbhhbbbbbhhhhshhshhhbbbbbbbbbbbhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhssshbbbhhhhhhhhhhhhhhhhhhssshhhhhhhhhhhhhhshhhhhhsssshhhbhhhhhhhhhhhsshhhhhhhhhhbhhhhhhhbbbbbbhbbhhhhhhhhhhhsshhsshshshhshhshhhhsssshssshhssssssssssssssssshhbbbbhbhhhssshhbhhshhsshhhhhhhhhhhhhhbbbbbbbbhhbhhhshsssshhhhhhhhshhssshhhhhhhhhhhhhhhhbbbbbbbbbbbbbbhbbhhhbbbbbbbbbbbbbbbbhhhhsshhhhshhhbbbhhhhhhhhhhsshhhhhhhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhshhhbhshhhhshhssshssssssshhhhssssssshssssssssssshhbhhhhbbbhhhbbbbbbbbbbbbbbbbbbbbbbbbbbbhhhhhhhhhhsssssshssshsssssssshhhbbbbhbhhhbbbhhhhhhhhsshssssssssshhshhhhhshsssssshssshhhbhbbbbbbhhhbhhhhhhhshhshhhhshhhshhsssshhhhhhhhhhhbbbbbbbbbbbbbbbbbbbbbbbbbhhhbhhhhhhhbbbbbhhhshhsssshhhhhhhhsssssssshshhhhhhhbbbhhhhhhhhhhsshsssshhhhhhhhhhhssssssssssssssshhhhhhhhhhhhhhhhbhhhhhhshhhhhbbbbbbbbbbbbbbbbbbbbbbbbbbbhhhhhhbhhhhhhhbbbbhhhhhhhhhhhhhshhsshhsssshhshhhhhhhhhhhshbhhhhhbbbbbhbbbhhhhhhhhhhhhhhhsshhhhhhbhhhhsssssssshhhssshhssssssssssssssshsssshhhbbbhhsssshhhhhhhhhhhhhhhhhbbbbbbbbbbbbbbbbbbbbbbbbbbbhbhhhbbhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhbhhhhhhhhhhhshhhsssssssshhhhhhhhshshsssssssshsshhhhssssssssssshhhhhhhhhhhhhhhhhhhhhhhhbbbhbbbbbbhhhhhhhhhhbbbhshhhhhhhbbbbbbbbbbbhbbbhbbbbhhhhhshhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhshbhhhhhhshhshhhhhhhbbhhsssssssssssssssssssssssssssshhhshhshshhhbhhhhbbbhhbbbbbbbbbbbbbhhsssshhhhsssshhhhhhhsssshhhhhbhbhhhhshhhhhhhhhbbbbbbbhhhhhhhhssssshhhshhshhhbshhhhhsssssshshhhhhhhhhhhbbhhshshhhhhhhhhbbbbbbbbbbbbhhhsssshshhhhhhhhhsshhssshhshhhhhhbhsshhhhhhhhhhhhhhhhbbhsshhhhhhhhhhhhbhhhbhhhhhhhhbhhhbhhbbbbbbbbbbbbbbbbbbbbbbbbhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshssssshbhhhbbbbhbhhhhhhhhhhhhhhhhhhhhhhsshshshhbhbbbhhhhhhhhhhsssshhhhhbhhhhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshssshhsshhssssssssssssssssssssssssshshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbbhhbhhhbbbbbhbbbhbhhbbbbhhbhhhhhhhhhssshsssssssssssssssshhhhhhhhhhhhhhhhbhhshhhhhhbhhshhhhhhhbbbbhhbhhhhhssssbhsshhhhhhhhhhhhhhhhhhhhhhhhhbbbbhhhbhhbbhhhsshhhhhhhhhhhshhssshhhhhshhhhhhhhhhhhhhhhhhbbbhbbbbbbbbbbbhhhhhhhbbbbbbbbbbbbbbbbbhhhhsssshhhbhhhhbbbhbhhhhhhhhshssssshshssssssssshsssssssssssssssshhhhhhhhhhhbhhhhhbbbbbbbbbbbbbbbbbbbbbbbhhhsshhhhhhhhhbbbhbbhhhhhhhssssssssssssssssssssssssssshhhhhhhhhhhhhhhhhhhhhhhhhhhbbbbbbbbbhhhssssshhhhhhhhhsshshhshhhhhhhhhhhhhhhhhhhbhbbbbhhhbhhbbbbbbbbbbbbhhhbbbbbbbbhbbhbbbhbhhhhhhhhhhhssshhbhhhbbhhhhhhsshhbbhhhhhhshhhhbhhhhhsshhhhhshhhbbbhhhhhhhhhhhhhhhhhhhhssshhbhshssssssshhhsshshshhhbhhhbbbbbbbbbbbhhbhhhhhhhhhbhhhhhhhhshshhhbbhhhhhhsshhhhssbhhhhhhhhsshhbhhhhhhhbhhhbhhhhhhhhhhhsshhhhshhhhhhhhsssssssssshssshhhhhssssssssssssshshhhhhhbhhhshhhhhhhhhhhhhhhbbbbbbbbbhbbbhbbhhbbbbbbbbhbbbbhhhhhhhhhhhhbhbbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhshhhhhhhhhbbhhhhhssssshhbbbbhhhhhhhhshhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshsshssshhhhhhhhhhhhsshhhhhhbhhhssssshhhhhhhhhsshssssssssssssssssshhhhbbbbbbbbbbbbbbbbbbbhhhhbhbbbbbhhhhhhhhhhhhhsshhhhhhhhhhhhhhbbhbbbhhhhhbhhhhhhhhhhbhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshshhhhhshsshhbhhhhhhhhhbhhhhbhhhhhbhhhbhhhhhhhhhhhhsssshhhsssssshshsssshhhhhhhhsssssssssssssssshhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhbbbbbbbbbbbbbbhhbhhshhbhhshshhhbhbhhhsshhhbbbbbbbbbbbbbbbbbbbhhhhhhhhhsbhhhhhhhhhhhhhssssssssssshsshhhbbhhhhssssshshsshssshhhbbhhbbhhbbbbbbhhbhhhbhhhhhssssssssshssssssssssssshhhhhhhhhbbbbhbhhhhbbbbbbhhhhhhhsssssshhshsshhhhhshhhshhhhhhhhhhhhhhhbbhbbhhbbhsssssshhhbbbhhssshhhbhhhhhhhhhhhhhhshhhhhhhhhhhhhhbbhhhsshhhhhhhhhhhhbhhshhhhhhhhhhhhhhhhhhhhbhhbbbbbbbbhsshhhhhhhhhhhhbhhsssssssshbbhhshhhhhbhhhhhbbbbhhhbbhbbbbbbhbbbbbbhhhbbhhhhhhhbhhhhbbbbbbbbhhhhshhbbhhhhhhhhhhhhhhhhhhhssssshsshsshshshhhhhhbhhbbbbbbhhhhsshsssssssssssssssssssshhssshhhhhhhhssshhhhhhhhhbhbhsshhhhhhhbbhhhhhhsshhhhbhbshhhhshhhhhhhhhhhhhhhhbbbhhhhhhbbbbbbbbbhhsshhhhhhhsshhhhhhshssshhhhsshhsshhhhbbbbbbbbbbbbbbbbbbhhhhhbhhhhhsssssssssshssshhhhhhbhbbbbbbbbbbbbbbbbbbbbbbbhhhbhhhhbhhhshhsshsssshhhhsshhhhbbbbbhhhhhssssssssssssssssssssbbbbbbbbbbbbhbhhbbhhhhhhbbhhhhbhhhbbhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhssssshhbbhbbhhbhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhshshhhhhhhshhbbhhhhhhhhhhhhhhbhhhshbbhhhhhshhhhhhhhhhssssssssssssssssssssssssssssssshhhhhhhhhbbhbbbhbbbhhhhhhhhhhhhhhhhhbbbbhhhbhhbhhhhhhsssssssssssssshhhhhhhhhhhhhhhbbbbbbbbbbbbhhhhhhhhhhhhbhhhhhhhhhhhhhhhshbbbbbbbbbhbbbbhhhbbhhbhbbhbbhhssssshsshhbhhbhbhhhshsshhssssssssssshssshshhhhhbhhhhhhbbhhhhhsssssssshhbbbhhhhbbbbbhbbbbhhbhhhbbbbbbbbbbbbbbhhhhhsssshshhbbhhhhhhhshhsssshsssshhhshhhhsssssssssssssssssshhhshhhhhhbbbbhhhbbbbbhhhhhhhshhshssshhssshhhhhbbbbbbbbbbbhhbbbbbbbbbbbbbhhbbbbhhhhhhssssssssshhhhhhhhhhhhhhbbbbbbhhbbbbhbhbhhssshhhssssssssssssshhsshshsssssssssssshhhshhhhhhhhhbbbhbhhhhhhhbhhhbhbhhhbhbbbbbbbbhbbbbbhhhhhssssssshhshhhbbbbbbbbbbbbbbbhhshhbbbhhbhhbhhhhhhhhshhhhhhbhhhhhhhhhhhhssshhhssssssssshshhhhbhbbbbhhbhhhhhshhbhhhhhbbbbhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshhhhssshhhhhhhhhhhshshhhhhhhhbbbhhbbhhbbhhhhhhsssshhshbbhhhhhhhhhhhshhbbbbhhhhhhhhssssshhhbbhhhhhhhhhbbbhhhsssssshssssssssssssssshhsssssssssshhhhhhhhbbbbbbbbbbbbbbbbbbhhssssssssssshshhbbbhhhhhhhhhhshhhhhhhhhhhhhhhhsssssshsshshhhhhhhhhhhhbbbhbhhhhhbhhhssssshhhhhhhhhhhhhhhhhbhhbbbbbhsssssshhhhhhhhhhhhbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbhhhssssssssssssssssssssshshshsshhshhhsshhsshhhhhhhhhhhhhhhhhhsshhhhhhhhhbhhhhshhhhhhhhhhbbhhhhhhhhhhshhhhhbbbhbbbbbbbbbbbbbbbbbbbbhhhhhhhhhhhbbbbbhhbbhhbhhhhsshhhhhhbbhhhhhshhhhhhhhhsshhhbhbbhhhhhhhhhhshhsshhhhssssssssssssssssssssssssssssshhhhhbhbhhbbbhhhshhhhhsssshhhhhhhhhhhhhbhhhshhhhbhhhhhhbbbbbbbbbbbbbbbbbbbbbbhhhhhhhhhbhhhhhhhhhhbhhhhhhhhhhhhhshhhhshhhhhhhhhbhhsssssssssssssssssssssssshhhhbhbhhhhhhhhhhhhhhhhhhhhhhhhbhhhh"

BASKETS_TRADES = "shshhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhhhhhhhhhhhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhssshhhhhhhbbhhhhhhhhhhhhhhbhhhhhbhhhhhhhhhhhhhssshhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhbhhhhhhhhhhhshhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhssshhhhhhhhhhhhhhhhhhhbbhhhhhhhhhhhhhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhssshhhhhhhhhhhhhhhhhhhhhhhhhhbbhhhhhhhhhshshhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhssshhhhhhhhbhhhhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbhhhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhssshshhhhhhhhhhbhbbbhhhhhhhhhhhhhhhhhhhhssshhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhbhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshshhhhhhhhbbhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhsshhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhbhhhhhhhhhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshshshhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhbhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhshsshhhhhhhhhhhhhhhhhhhhhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhshhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshshhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshhhhhhhhhhhhhhhhhhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhshhhhhhhshshhhhhhhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhbhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhbbhbhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshshhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhbbhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhhhhhhhhhhhhhhsshhhhhhhhhhhhhhhshhhhhhhhhhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshhhhhhhhhhhhhhhhhhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhbhhhhhhhhhshshhhhhhhhhshhhhbbhhhhhhhhhbhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhhhbbhhhhhhhhhhhhhhhhhhhhhhhshshhsshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbhhhhhhhhhhhhhhhhhhhhhshshhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshsshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhbhhhhhhhhhhhhhsshhhhhhhhhhhhhhhhhhbbbhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhsshhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhhhhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhsshhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbbhhhhhhhhhhhhhhhshshhshhhhhhhhhhhhhhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhssshshhhhhhhhhhhhhhhhhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhsshhhhhhhhhhhhbhhbbbhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhssshhhhhhhhhhhhhhhhhbbbhhhhhhhhhhhbhhhhhhhhhshhsshshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhssshhhhhhbhhhhhhhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhssshhhhhhhhhhhhhhhhhhhhhhhhhhhhbhbhhhhhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhsshshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhbbhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhbbbhhhhhhhhhhhhhhhhhhhhhhhhhshhssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhhhhhhhbhhbhhhhhhhhhhhhhhhhhhhhhhssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhshhhhhhhhhhhhhhhhhhhhhhhhbbhhhhhhhhhhhhhhhsshsshhhhhhhhhhhhbbbhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhsshhhhhhhhhhhhbhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhbbbhhhhhhhhhhhhhhhhhhhhhhsshhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhbbhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshhhhhhhhhshhhhhhhhhhhhhhhhhhhhbbhhhhhhhhhhhhhhhhhhhsshhhhhhhhhhhhhbbhhhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshshhhhhhhhhhsshhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhbbhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshsshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhbhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshsshhhhhhhhhhhhhhhhhhhhhhbhbbhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhbbbhhbhhhhhhhhhhhhhhhhhhhhhhhsshhhsshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhbbhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhbhbbhhhhhhhhhhhhhhhhhhhhhhhhshhhshhhshshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbhhhhhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshhhhhhhbhhhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhhhhbhhhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsssshhhhhhhhhhhbhhbhhhhhhhhhhhhbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhbbhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhsshhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhhhhhhbhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhsshhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhssshshhhhhhhhhhhhhhhhhhhbhhhhhhbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhsshhsshhhhhhhhhhhhhhhhhhhhhhhhhhhbbbhhhhhhhhhhhsshhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhhhhhhhhhhhhhhhhhhhbhbhhbhhhhhhhhhhhsssshhhhhhhhhhhhhhhhhhhhhhhhhhbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhssshhhhhhhhhhhbbhbbhhhhhhhhhhhhhhhhhhhhhhhshshhhhhhhhhhhhshhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbbhhhhhhhhhhsshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbhhbbhhhbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhhhhhhhhhhhhhhhhhhhhshhhhhhhhsshhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh"


class Product:
    AMETHYSTS = "AMETHYSTS"
    STARFRUIT = "STARFRUIT"
    ORCHIDS = "ORCHIDS"
    GIFT_BASKET = "GIFT_BASKET"
    CHOCOLATE = "CHOCOLATE"
    STRAWBERRIES = "STRAWBERRIES"
    ROSES = "ROSES"
    SYNTHETIC = "SYNTHETIC"
    SPREAD = "SPREAD"
    COCONUT = "COCONUT"
    COCONUT_COUPON = "COCONUT_COUPON"


PARAMS = {
    Product.AMETHYSTS: {
        "fair_value": 10000,
        "take_width": 1,
        "clear_width": 0.5,
        "volume_limit": 0,
    },
    Product.STARFRUIT: {
        "take_width": 1,
        "clear_width": 0,
        "prevent_adverse": True,
        "adverse_volume": 15,
        "reversion_beta": -0.229,
        "starfruit_min_edge": 2,
    },
    Product.ORCHIDS: {
        "make_edge": 2,
        "make_probability": 0.800,
    },
}


class Trader:
    def __init__(self, params=None):
        if params is None:
            params = PARAMS
        self.params = params

        self.LIMIT = {
            Product.AMETHYSTS: 20,
            Product.STARFRUIT: 20,
            Product.ORCHIDS: 100,
            Product.GIFT_BASKET: 60,
            Product.CHOCOLATE: 250,
            Product.STRAWBERRIES: 350,
            Product.ROSES: 60,
            Product.COCONUT: 300,
            Product.COCONUT_COUPON: 600,
        }

        self.TRACK_PNL = [
            Product.CHOCOLATE,
            Product.GIFT_BASKET,
            Product.STRAWBERRIES,
            Product.ROSES,
            Product.COCONUT,
            Product.COCONUT_COUPON,
        ]

        self.ESTIMATED_SPREAD = {
            Product.CHOCOLATE: 0.55,
            Product.GIFT_BASKET: 6,
            Product.STRAWBERRIES: 0.55,
            Product.ROSES: 0.55,
            Product.COCONUT: 0.99,
            Product.COCONUT_COUPON: 0.6,
        }

        self.STOP_LOSS_PNL = {
            Product.CHOCOLATE: 0,
            Product.GIFT_BASKET: 0,
            Product.STRAWBERRIES: 0,
            Product.ROSES: 0,
            Product.COCONUT: 0,
            Product.COCONUT_COUPON: 0,
        }

    # Returns buy_order_volume, sell_order_volume
    def take_best_orders(
        self,
        product: str,
        fair_value: int,
        take_width: float,
        orders: List[Order],
        order_depth: OrderDepth,
        position: int,
        buy_order_volume: int,
        sell_order_volume: int,
        prevent_adverse: bool = False,
        adverse_volume: int = 0,
    ) -> (int, int):
        position_limit = self.LIMIT[product]
        if len(order_depth.sell_orders) != 0:
            best_ask = min(order_depth.sell_orders.keys())
            best_ask_amount = -1 * order_depth.sell_orders[best_ask]

            if best_ask <= fair_value - take_width:
                quantity = min(
                    best_ask_amount, position_limit - position
                )  # max amt to buy
                if quantity > 0:
                    orders.append(Order(product, best_ask, quantity))
                    buy_order_volume += quantity
                    order_depth.sell_orders[best_ask] += quantity
                    if order_depth.sell_orders[best_ask] == 0:
                        del order_depth.sell_orders[best_ask]

        if len(order_depth.buy_orders) != 0:
            best_bid = max(order_depth.buy_orders.keys())
            best_bid_amount = order_depth.buy_orders[best_bid]
            if best_bid >= fair_value + take_width:
                quantity = min(
                    best_bid_amount, position_limit + position
                )  # should be the max we can sell
                if quantity > 0:
                    orders.append(Order(product, best_bid, -1 * quantity))
                    sell_order_volume += quantity
                    order_depth.buy_orders[best_bid] -= quantity
                    if order_depth.buy_orders[best_bid] == 0:
                        del order_depth.buy_orders[best_bid]
        return buy_order_volume, sell_order_volume

    def take_best_orders_with_adverse(
        self,
        product: str,
        fair_value: int,
        take_width: float,
        orders: List[Order],
        order_depth: OrderDepth,
        position: int,
        buy_order_volume: int,
        sell_order_volume: int,
        adverse_volume: int,
    ) -> (int, int):

        position_limit = self.LIMIT[product]
        if len(order_depth.sell_orders) != 0:
            best_ask = min(order_depth.sell_orders.keys())
            best_ask_amount = -1 * order_depth.sell_orders[best_ask]
            if abs(best_ask_amount) <= adverse_volume:
                if best_ask <= fair_value - take_width:
                    quantity = min(
                        best_ask_amount, position_limit - position
                    )  # max amt to buy
                    if quantity > 0:
                        orders.append(Order(product, best_ask, quantity))
                        buy_order_volume += quantity
                        order_depth.sell_orders[best_ask] += quantity
                        if order_depth.sell_orders[best_ask] == 0:
                            del order_depth.sell_orders[best_ask]

        if len(order_depth.buy_orders) != 0:
            best_bid = max(order_depth.buy_orders.keys())
            best_bid_amount = order_depth.buy_orders[best_bid]
            if abs(best_bid_amount) <= adverse_volume:
                if best_bid >= fair_value + take_width:
                    quantity = min(
                        best_bid_amount, position_limit + position
                    )  # should be the max we can sell
                    if quantity > 0:
                        orders.append(Order(product, best_bid, -1 * quantity))
                        sell_order_volume += quantity
                        order_depth.buy_orders[best_bid] -= quantity
                        if order_depth.buy_orders[best_bid] == 0:
                            del order_depth.buy_orders[best_bid]

        return buy_order_volume, sell_order_volume

    def market_make(
        self,
        product: str,
        orders: List[Order],
        bid: int,
        ask: int,
        position: int,
        buy_order_volume: int,
        sell_order_volume: int,
    ) -> (int, int):
        buy_quantity = self.LIMIT[product] - (position + buy_order_volume)
        if buy_quantity > 0:
            orders.append(Order(product, round(bid), buy_quantity))  # Buy order

        sell_quantity = self.LIMIT[product] + (position - sell_order_volume)
        if sell_quantity > 0:
            orders.append(Order(product, round(ask), -sell_quantity))  # Sell order
        return buy_order_volume, sell_order_volume

    def clear_position_order(
        self,
        product: str,
        fair_value: float,
        width: int,
        orders: List[Order],
        order_depth: OrderDepth,
        position: int,
        buy_order_volume: int,
        sell_order_volume: int,
    ) -> List[Order]:
        position_after_take = position + buy_order_volume - sell_order_volume
        fair_for_bid = round(fair_value - width)
        fair_for_ask = round(fair_value + width)

        buy_quantity = self.LIMIT[product] - (position + buy_order_volume)
        sell_quantity = self.LIMIT[product] + (position - sell_order_volume)

        if position_after_take > 0:
            # Aggregate volume from all buy orders with price greater than fair_for_ask
            clear_quantity = sum(
                volume
                for price, volume in order_depth.buy_orders.items()
                if price >= fair_for_ask
            )
            clear_quantity = min(clear_quantity, position_after_take)
            sent_quantity = min(sell_quantity, clear_quantity)
            if sent_quantity > 0:
                orders.append(Order(product, fair_for_ask, -abs(sent_quantity)))
                sell_order_volume += abs(sent_quantity)

        if position_after_take < 0:
            # Aggregate volume from all sell orders with price lower than fair_for_bid
            clear_quantity = sum(
                abs(volume)
                for price, volume in order_depth.sell_orders.items()
                if price <= fair_for_bid
            )
            clear_quantity = min(clear_quantity, abs(position_after_take))
            sent_quantity = min(buy_quantity, clear_quantity)
            if sent_quantity > 0:
                orders.append(Order(product, fair_for_bid, abs(sent_quantity)))
                buy_order_volume += abs(sent_quantity)

        return buy_order_volume, sell_order_volume

    def starfruit_fair_value(self, order_depth: OrderDepth, traderObject) -> float:
        if len(order_depth.sell_orders) != 0 and len(order_depth.buy_orders) != 0:
            best_ask = min(order_depth.sell_orders.keys())
            best_bid = max(order_depth.buy_orders.keys())
            filtered_ask = [
                price
                for price in order_depth.sell_orders.keys()
                if abs(order_depth.sell_orders[price])
                >= self.params[Product.STARFRUIT]["adverse_volume"]
            ]
            filtered_bid = [
                price
                for price in order_depth.buy_orders.keys()
                if abs(order_depth.buy_orders[price])
                >= self.params[Product.STARFRUIT]["adverse_volume"]
            ]
            mm_ask = min(filtered_ask) if len(filtered_ask) > 0 else None
            mm_bid = max(filtered_bid) if len(filtered_bid) > 0 else None
            if mm_ask == None or mm_bid == None:
                if traderObject.get("starfruit_last_price", None) == None:
                    mmmid_price = (best_ask + best_bid) / 2
                else:
                    mmmid_price = traderObject["starfruit_last_price"]
            else:
                mmmid_price = (mm_ask + mm_bid) / 2

            if traderObject.get("starfruit_last_price", None) != None:
                last_price = traderObject["starfruit_last_price"]
                last_returns = (mmmid_price - last_price) / last_price
                pred_returns = (
                    last_returns * self.params[Product.STARFRUIT]["reversion_beta"]
                )
                fair = mmmid_price + (mmmid_price * pred_returns)
            else:
                fair = mmmid_price
            traderObject["starfruit_last_price"] = mmmid_price
            return fair
        return None

    def make_amethyst_orders(
        self,
        order_depth: OrderDepth,
        fair_value: int,
        position: int,
        buy_order_volume: int,
        sell_order_volume: int,
        volume_limit: int,
    ) -> (List[Order], int, int):
        orders: List[Order] = []
        baaf = min(
            [
                price
                for price in order_depth.sell_orders.keys()
                if price > fair_value + 1
            ]
        )
        bbbf = max(
            [price for price in order_depth.buy_orders.keys() if price < fair_value - 1]
        )

        if baaf <= fair_value + 2:
            if position <= volume_limit:
                baaf = fair_value + 3  # still want edge 2 if position is not a concern

        if bbbf >= fair_value - 2:
            if position >= -volume_limit:
                bbbf = fair_value - 3  # still want edge 2 if position is not a concern

        buy_order_volume, sell_order_volume = self.market_make(
            Product.AMETHYSTS,
            orders,
            bbbf + 1,
            baaf - 1,
            position,
            buy_order_volume,
            sell_order_volume,
        )
        return orders, buy_order_volume, sell_order_volume

    def take_orders(
        self,
        product: str,
        order_depth: OrderDepth,
        fair_value: float,
        take_width: float,
        position: int,
        prevent_adverse: bool = False,
        adverse_volume: int = 0,
    ) -> (List[Order], int, int):
        orders: List[Order] = []
        buy_order_volume = 0
        sell_order_volume = 0

        if prevent_adverse:
            buy_order_volume, sell_order_volume = self.take_best_orders_with_adverse(
                product,
                fair_value,
                take_width,
                orders,
                order_depth,
                position,
                buy_order_volume,
                sell_order_volume,
                adverse_volume,
            )
        else:
            buy_order_volume, sell_order_volume = self.take_best_orders(
                product,
                fair_value,
                take_width,
                orders,
                order_depth,
                position,
                buy_order_volume,
                sell_order_volume,
            )
        return orders, buy_order_volume, sell_order_volume

    def clear_orders(
        self,
        product: str,
        order_depth: OrderDepth,
        fair_value: float,
        clear_width: int,
        position: int,
        buy_order_volume: int,
        sell_order_volume: int,
    ) -> (List[Order], int, int):
        orders: List[Order] = []
        buy_order_volume, sell_order_volume = self.clear_position_order(
            product,
            fair_value,
            clear_width,
            orders,
            order_depth,
            position,
            buy_order_volume,
            sell_order_volume,
        )
        return orders, buy_order_volume, sell_order_volume

    def make_starfruit_orders(
        self,
        order_depth: OrderDepth,
        fair_value: float,
        min_edge: float,
        position: int,
        buy_order_volume: int,
        sell_order_volume: int,
    ) -> (List[Order], int, int):
        orders: List[Order] = []
        aaf = [
            price
            for price in order_depth.sell_orders.keys()
            if price >= round(fair_value + min_edge)
        ]
        bbf = [
            price
            for price in order_depth.buy_orders.keys()
            if price <= round(fair_value - min_edge)
        ]
        baaf = min(aaf) if len(aaf) > 0 else round(fair_value + min_edge)
        bbbf = max(bbf) if len(bbf) > 0 else round(fair_value - min_edge)
        buy_order_volume, sell_order_volume = self.market_make(
            Product.STARFRUIT,
            orders,
            bbbf + 1,
            baaf - 1,
            position,
            buy_order_volume,
            sell_order_volume,
        )

        return orders, buy_order_volume, sell_order_volume

    def orchids_implied_bid_ask(
        self,
        observation: ConversionObservation,
    ) -> (float, float):
        return (
            observation.bidPrice
            - observation.exportTariff
            - observation.transportFees
            - 0.1,
            observation.askPrice + observation.importTariff + observation.transportFees,
        )

    def orchids_arb_take(
        self,
        order_depth: OrderDepth,
        observation: ConversionObservation,
        position: int,
    ) -> (List[Order], int, int):
        orders: List[Order] = []
        position_limit = self.LIMIT[Product.ORCHIDS]
        buy_order_volume = 0
        sell_order_volume = 0

        implied_bid, implied_ask = self.orchids_implied_bid_ask(observation)

        buy_quantity = position_limit - position
        sell_quantity = position_limit + position

        ask = round(observation.askPrice) - 2

        if ask > implied_ask:
            edge = (ask - implied_ask) * self.params[Product.ORCHIDS][
                "make_probability"
            ]
        else:
            edge = 0

        for price in sorted(list(order_depth.sell_orders.keys())):
            if price > implied_bid - edge:
                break

            if price < implied_bid - edge:
                quantity = min(
                    abs(order_depth.sell_orders[price]), buy_quantity
                )  # max amount to buy
                if quantity > 0:
                    orders.append(Order(Product.ORCHIDS, round(price), quantity))
                    buy_order_volume += quantity

        for price in sorted(list(order_depth.buy_orders.keys()), reverse=True):
            if price < implied_ask + edge:
                break

            if price > implied_ask + edge:
                quantity = min(
                    abs(order_depth.buy_orders[price]), sell_quantity
                )  # max amount to sell
                if quantity > 0:
                    orders.append(Order(Product.ORCHIDS, round(price), -quantity))
                    sell_order_volume += quantity

        return orders, buy_order_volume, sell_order_volume

    def orchids_arb_clear(self, position: int) -> int:
        conversions = -position
        return conversions

    def orchids_arb_make(
        self,
        observation: ConversionObservation,
        position: int,
        buy_order_volume: int,
        sell_order_volume: int,
    ) -> (List[Order], int, int):
        orders: List[Order] = []
        position_limit = self.LIMIT[Product.ORCHIDS]

        # Implied Bid = observation.bidPrice - observation.exportTariff - observation.transportFees - 0.1
        # Implied Ask = observation.askPrice + observation.importTariff + observation.transportFees
        implied_bid, implied_ask = self.orchids_implied_bid_ask(observation)

        aggressive_ask = round(observation.askPrice) - 2
        aggressive_bid = round(observation.bidPrice) + 2

        if aggressive_bid < implied_bid:
            bid = aggressive_bid
        else:
            bid = implied_bid - 1

        if aggressive_ask >= implied_ask + 0.5:
            ask = aggressive_ask
        elif aggressive_ask + 1 >= implied_ask + 0.5:
            ask = aggressive_ask + 1
        else:
            ask = implied_ask + 2

        buy_quantity = position_limit - (position + buy_order_volume)
        if buy_quantity > 0:
            orders.append(Order(Product.ORCHIDS, round(bid), buy_quantity))

        sell_quantity = position_limit + (position - sell_order_volume)
        if sell_quantity > 0:
            orders.append(Order(Product.ORCHIDS, round(ask), -sell_quantity))

        return orders, buy_order_volume, sell_order_volume

    def get_swmid(self, order_depth) -> float:
        best_bid = max(order_depth.buy_orders.keys())
        best_ask = min(order_depth.sell_orders.keys())
        best_bid_vol = abs(order_depth.buy_orders[best_bid])
        best_ask_vol = abs(order_depth.sell_orders[best_ask])
        return (best_bid * best_ask_vol + best_ask * best_bid_vol) / (
            best_bid_vol + best_ask_vol
        )

    def calculate_pnl(self, order_depths, position, traderObject):
        pnls = {}
        for product in self.TRACK_PNL:
            product_position = position.get(product, 0)
            pnl_key = f"{product}_pnl"
            cash_key = f"{product}_cash"
            last_position_key = f"{product}_last_position"
            prev_mid_key = f"{product}_last_mid_price"

            if pnl_key not in traderObject:
                traderObject[pnl_key] = 0
            if cash_key not in traderObject:
                traderObject[cash_key] = 0
            if last_position_key not in traderObject:
                traderObject[last_position_key] = 0

            curr_pnl = traderObject[pnl_key]
            curr_cash = traderObject[cash_key]
            position_diff = traderObject[last_position_key] - product_position

            # update position
            traderObject[last_position_key] = product_position

            if product not in order_depths:
                continue

            best_bid = (
                max(order_depths[product].buy_orders.keys())
                if order_depths[product].buy_orders
                else None
            )
            best_ask = (
                min(order_depths[product].sell_orders.keys())
                if order_depths[product].sell_orders
                else None
            )

            mid_price = None
            if best_bid is None or best_ask is None:
                continue
            else:
                mid_price = (best_bid + best_ask) / 2

            if prev_mid_key not in traderObject:
                traderObject[prev_mid_key] = mid_price

            prev_mid_price = traderObject[prev_mid_key]

            curr_cash = (
                curr_cash
                + position_diff * prev_mid_price
                + abs(position_diff) * -self.ESTIMATED_SPREAD[product]
            )
            curr_pnl = curr_cash + product_position * mid_price

            # update cash, pnl
            traderObject[cash_key] = curr_cash
            traderObject[pnl_key] = curr_pnl
            traderObject[prev_mid_key] = mid_price
        for product in self.TRACK_PNL:
            cash_key = f"{product}_cash"
            pnl_key = f"{product}_pnl"
            pnls[product] = traderObject[pnl_key]
            print(f"{product} PNL: {traderObject[pnl_key]}")
        return pnls

    def stoploss(self, timestamp, pnls):
        if timestamp < 75000:
            return []
        stops = []
        for product, limit in self.STOP_LOSS_PNL.items():
            product_pnl = pnls.get(product, None)
            if product_pnl is None:
                continue
            if product_pnl < limit:
                stops.append(product)
        return stops

    def roses_order(
        self, order_depth: OrderDepth, position: int, timestamp: int
    ) -> List[Order]:
        iteration = int(timestamp / 100)
        signal = ROSES_TRADES[iteration]
        best_bid = max(order_depth.buy_orders.keys())
        worst_bid = min(order_depth.buy_orders.keys())
        best_ask = min(order_depth.sell_orders.keys())
        worst_ask = max(order_depth.sell_orders.keys())
        mid_price = (best_bid + best_ask) / 2

        if signal == "b":
            target_volume = self.LIMIT[Product.ROSES] - position
            if target_volume > 0:
                return [Order(Product.ROSES, worst_ask, target_volume)]
            else:
                return []

        elif signal == "s":
            target_volume = -self.LIMIT[Product.ROSES] - position
            if target_volume < 0:
                return [Order(Product.ROSES, worst_bid, target_volume)]
            else:
                return []

        else:
            return []

    def baskets_order(
        self, order_depth: OrderDepth, position: int, timestamp: int
    ) -> List[Order]:
        iteration = int(timestamp / 100)
        signal = BASKETS_TRADES[iteration]

        mm_bids = [
            level
            for level in order_depth.buy_orders.keys()
            if order_depth.buy_orders[level] >= 10
        ]
        mm_asks = [
            level
            for level in order_depth.sell_orders.keys()
            if abs(order_depth.sell_orders[level]) >= 10
        ]

        if len(mm_bids) == 0 or len(mm_asks) == 0:
            return []

        mm_bid = min(mm_bids)
        mm_ask = max(mm_asks)

        if signal == "b":
            target_volume = self.LIMIT[Product.GIFT_BASKET] - position
            if target_volume > 0:
                return [Order(Product.GIFT_BASKET, mm_ask, target_volume)]
            else:
                return []
        elif signal == "s":
            target_volume = -self.LIMIT[Product.GIFT_BASKET] - position
            if target_volume < 0:
                return [Order(Product.GIFT_BASKET, mm_bid, target_volume)]
            else:
                return []
        elif signal == "c":
            target_volume = 0 - position
            if target_volume < 0:
                return [Order(Product.GIFT_BASKET, mm_bid, target_volume)]
            elif target_volume > 0:
                return [Order(Product.GIFT_BASKET, mm_ask, target_volume)]
            else:
                return []
        else:
            return []

    def coconut_order(
        self, order_depth: OrderDepth, position: int, timestamp: int
    ) -> List[Order]:
        iteration = int(timestamp / 100)
        signal = COCONUT_TRADES[iteration]
        best_bid = max(order_depth.buy_orders.keys())
        worst_bid = min(order_depth.buy_orders.keys())
        best_ask = min(order_depth.sell_orders.keys())
        worst_ask = max(order_depth.sell_orders.keys())
        mid_price = (best_bid + best_ask) / 2

        if signal == "b":
            target_volume = self.LIMIT[Product.COCONUT] - position
            if target_volume > 0:
                return [Order(Product.COCONUT, worst_ask, target_volume)]
            else:
                return []

        elif signal == "s":
            target_volume = -self.LIMIT[Product.COCONUT] - position
            if target_volume < 0:
                return [Order(Product.COCONUT, worst_bid, target_volume)]
            else:
                return []
        else:
            return []

    def coconut_coupon_order(
        self, order_depth: OrderDepth, position: int, timestamp: int
    ) -> List[Order]:
        iteration = int(timestamp / 100)
        signal = COCONUT_COUPON_TRADES[iteration]
        best_bid = max(order_depth.buy_orders.keys())
        worst_bid = min(order_depth.buy_orders.keys())
        best_ask = min(order_depth.sell_orders.keys())
        worst_ask = max(order_depth.sell_orders.keys())
        mid_price = (best_bid + best_ask) / 2

        if signal == "b":
            target_volume = self.LIMIT[Product.COCONUT_COUPON] - position
            if target_volume > 0:
                return [Order(Product.COCONUT_COUPON, worst_ask, target_volume)]
            else:
                return []

        elif signal == "s":
            target_volume = -self.LIMIT[Product.COCONUT_COUPON] - position
            if target_volume < 0:
                return [Order(Product.COCONUT_COUPON, worst_bid, target_volume)]
            else:
                return []
        else:
            return []

    def run(self, state: TradingState):
        result = {}
        traderObject = {}
        if state.traderData != None and state.traderData != "":
            traderObject = jsonpickle.decode(state.traderData)

        conversions = 0
        timestamp = state.timestamp

        pnls = self.calculate_pnl(state.order_depths, state.position, traderObject)
        stops = self.stoploss(timestamp, pnls)

        print(f"STOPS: {stops}")

        if Product.AMETHYSTS in self.params and Product.AMETHYSTS in state.order_depths:
            amethyst_position = (
                state.position[Product.AMETHYSTS]
                if Product.AMETHYSTS in state.position
                else 0
            )
            amethyst_take_orders, buy_order_volume, sell_order_volume = (
                self.take_orders(
                    Product.AMETHYSTS,
                    state.order_depths[Product.AMETHYSTS],
                    self.params[Product.AMETHYSTS]["fair_value"],
                    self.params[Product.AMETHYSTS]["take_width"],
                    amethyst_position,
                )
            )
            amethyst_clear_orders, buy_order_volume, sell_order_volume = (
                self.clear_orders(
                    Product.AMETHYSTS,
                    state.order_depths[Product.AMETHYSTS],
                    self.params[Product.AMETHYSTS]["fair_value"],
                    self.params[Product.AMETHYSTS]["clear_width"],
                    amethyst_position,
                    buy_order_volume,
                    sell_order_volume,
                )
            )
            amethyst_make_orders, _, _ = self.make_amethyst_orders(
                state.order_depths[Product.AMETHYSTS],
                self.params[Product.AMETHYSTS]["fair_value"],
                amethyst_position,
                buy_order_volume,
                sell_order_volume,
                self.params[Product.AMETHYSTS]["volume_limit"],
            )
            result[Product.AMETHYSTS] = (
                amethyst_take_orders + amethyst_clear_orders + amethyst_make_orders
            )

        if Product.STARFRUIT in self.params and Product.STARFRUIT in state.order_depths:
            starfruit_position = (
                state.position[Product.STARFRUIT]
                if Product.STARFRUIT in state.position
                else 0
            )
            starfruit_fair_value = self.starfruit_fair_value(
                state.order_depths[Product.STARFRUIT], traderObject
            )
            starfruit_take_orders, buy_order_volume, sell_order_volume = (
                self.take_orders(
                    Product.STARFRUIT,
                    state.order_depths[Product.STARFRUIT],
                    starfruit_fair_value,
                    self.params[Product.STARFRUIT]["take_width"],
                    starfruit_position,
                    self.params[Product.STARFRUIT]["prevent_adverse"],
                    self.params[Product.STARFRUIT]["adverse_volume"],
                )
            )
            starfruit_clear_orders, buy_order_volume, sell_order_volume = (
                self.clear_orders(
                    Product.STARFRUIT,
                    state.order_depths[Product.STARFRUIT],
                    starfruit_fair_value,
                    self.params[Product.STARFRUIT]["clear_width"],
                    starfruit_position,
                    buy_order_volume,
                    sell_order_volume,
                )
            )
            starfruit_make_orders, _, _ = self.make_starfruit_orders(
                state.order_depths[Product.STARFRUIT],
                starfruit_fair_value,
                self.params[Product.STARFRUIT]["starfruit_min_edge"],
                starfruit_position,
                buy_order_volume,
                sell_order_volume,
            )
            result[Product.STARFRUIT] = (
                starfruit_take_orders + starfruit_clear_orders + starfruit_make_orders
            )

        if Product.ORCHIDS in self.params and Product.ORCHIDS in state.order_depths:
            orchids_position = (
                state.position[Product.ORCHIDS]
                if Product.ORCHIDS in state.position
                else 0
            )

            conversions = self.orchids_arb_clear(orchids_position)

            orchids_position = 0

            orchids_take_orders, buy_order_volume, sell_order_volume = (
                self.orchids_arb_take(
                    state.order_depths[Product.ORCHIDS],
                    state.observations.conversionObservations[Product.ORCHIDS],
                    orchids_position,
                )
            )

            orchids_make_orders, _, _ = self.orchids_arb_make(
                state.observations.conversionObservations[Product.ORCHIDS],
                orchids_position,
                buy_order_volume,
                sell_order_volume,
            )

            result[Product.ORCHIDS] = orchids_take_orders + orchids_make_orders

        if Product.ROSES in state.order_depths and Product.ROSES not in stops:
            roses_position = (
                state.position[Product.ROSES] if Product.ROSES in state.position else 0
            )

            roses_order = self.roses_order(
                state.order_depths[Product.ROSES], roses_position, timestamp
            )
            if roses_order is not None and len(roses_order) > 0:
                result[Product.ROSES] = roses_order

        if (
            Product.GIFT_BASKET in state.order_depths
            and Product.GIFT_BASKET not in stops
        ):
            basket_position = (
                state.position[Product.GIFT_BASKET]
                if Product.GIFT_BASKET in state.position
                else 0
            )
            basket_order = self.baskets_order(
                state.order_depths[Product.GIFT_BASKET], basket_position, timestamp
            )
            if basket_order is not None and len(basket_order) > 0:
                result[Product.GIFT_BASKET] = basket_order
        if Product.COCONUT in state.order_depths and Product.COCONUT not in stops:
            coconut_position = (
                state.position[Product.COCONUT]
                if Product.COCONUT in state.position
                else 0
            )

            coconut_order = self.coconut_order(
                state.order_depths[Product.COCONUT], coconut_position, timestamp
            )
            if coconut_order is not None and len(coconut_order) > 0:
                result[Product.COCONUT] = coconut_order

        if (
            Product.COCONUT_COUPON in state.order_depths
            and Product.COCONUT_COUPON not in stops
        ):
            coconut_coupon_position = (
                state.position[Product.COCONUT_COUPON]
                if Product.COCONUT_COUPON in state.position
                else 0
            )
            coconut_coupon_order = self.coconut_coupon_order(
                state.order_depths[Product.COCONUT_COUPON],
                coconut_coupon_position,
                timestamp,
            )
            if coconut_coupon_order is not None and len(coconut_coupon_order) > 0:
                result[Product.COCONUT_COUPON] = coconut_coupon_order

        traderData = jsonpickle.encode(traderObject)

        return result, conversions, traderData
